### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by bcronje** [jniemann66/juddperft#5]
Under what license is juddperft?

**Comment by jniemann66** [comment]
Hi, it's under MIT license.
I've placed the license file in the repo. Thanks for the reminder ! I'd be interested to see what you do with it. regards, Judd

**Comment by bcronje** [comment]
Thank you for the response @jniemann66 and thank you for MIT license. I'm busy with my own hobby chess engine and I tend to not even look at GPL code. I have no idea where this pet project of mine is going, but I hope to learn some performance tricks from juddperft!

**Comment by jniemann66** [comment]
No problem @bcronje Good luck ! 

I hope my 4-bitboard method is not too confusing - I thought I was being clever at the time, but I think if I was going to write a new engine from scratch today, I might do it differently now. (All that boolean logic is enough to make your head explode !) 

I also have a full chess engine (that actually plays chess) , but  I'm keeping the code private for now, mainly because the evaluation function is embarrassingly bad :-) and needs work !

Anyway, from memory, the biggest performance boosts I got were from: 
a) being careful about what gets pushed on the stack (it's a real issue with recursive function calls) - keep the data passed in function calls small. 
b) the hash table - keep the entries small 
c) multithreading (obviously) 
d) keeping branching to a minimum (although not always - sometimes the compiled results may surprise you)

Cheers, 
Judd
